name: Lint
 
on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["main"]
 
jobs:
  pylint:
    runs-on: ubuntu-latest
 
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          # Install a specific version of uv.
          version: "0.12.7"
 
      - name: Install dependencies
        run: uv sync
 
      - name: Run pylint
        run: |
          src_files=$(git ls-files 'src/*.py' 'src/**/*.py')
          test_files=$(git ls-files 'tests/*.py' 'tests/**/*.py')

           if [ -z "$src_files" ] && [ -z "$test_files" ]; then
            echo "No Python files found, skipping pylint."
            exit 0
          fi

          exit_code=0

          if [ -n "$src_files" ]; then
            echo "Linting src/..."
            uv run pylint --source-roots=. src/ || exit_code=$?
          fi

          if [ -n "$test_files" ]; then
            echo "Linting tests/..."
            uv run pylint --source-roots=. tests/ || exit_code=$?
          fi

          exit $exit_code
